import type { Client, Regulation, WorkItem } from "@/lib/types";

export const clients: readonly Client[] = [
  {
    id: "sharma",
    name: "Sharma Pharmaceuticals Pvt. Ltd.",
    shortName: "Sharma Pharma",
    sector: "Pharma / Manufacturing",
    location: "Mumbai, Maharashtra",
    initials: "SP",
    risk: "high",
    riskScore: 8.6,
    pending: 3,
    dueThisWeek: 2,
    compliant: 12,
    source: "demo",
    identifiers: ["GSTIN 27AAACS1234F1ZA", "CIN U24200MH2015PTC123456"],
  },
  {
    id: "nexgen",
    name: "NexGen Software Solutions Pvt. Ltd.",
    shortName: "NexGen IT",
    sector: "IT / Software",
    location: "Bengaluru, Karnataka",
    initials: "NI",
    risk: "medium",
    riskScore: 5.2,
    pending: 1,
    dueThisWeek: 2,
    compliant: 18,
    source: "demo",
    identifiers: ["GSTIN 29AAACN5678G1ZB", "CIN U72200KA2018PTC234567"],
  },
  {
    id: "gupta",
    name: "Gupta Auto Components Ltd.",
    shortName: "Gupta Auto",
    sector: "Auto Ancillary",
    location: "Gurugram, Haryana",
    initials: "GA",
    risk: "high",
    riskScore: 8.1,
    pending: 4,
    dueThisWeek: 1,
    compliant: 9,
    source: "demo",
    identifiers: ["GSTIN 06AAACG9012H1ZC", "CIN U34300HR2012PLC045678"],
  },
  {
    id: "royal",
    name: "Royal Spice Kitchen Pvt. Ltd.",
    shortName: "Royal Spice",
    sector: "Food & Beverage",
    location: "New Delhi",
    initials: "RS",
    risk: "high",
    riskScore: 7.4,
    pending: 2,
    dueThisWeek: 3,
    compliant: 7,
    source: "demo",
    identifiers: ["GSTIN 07AAACR3456J1ZD", "FSSAI 13621011000123"],
  },
  {
    id: "lakshmi",
    name: "Lakshmi FinServ Pvt. Ltd.",
    shortName: "Lakshmi FinServ",
    sector: "NBFC",
    location: "Chennai, Tamil Nadu",
    initials: "LF",
    risk: "medium",
    riskScore: 6.1,
    pending: 2,
    dueThisWeek: 1,
    compliant: 22,
    source: "demo",
    identifiers: ["GSTIN 33AAACL7890K1ZE", "RBI B-13.00456"],
  },
  {
    id: "greenfield",
    name: "Greenfield Realty LLP",
    shortName: "Greenfield Realty",
    sector: "Real Estate",
    location: "Pune, Maharashtra",
    initials: "GR",
    risk: "low",
    riskScore: 3.2,
    pending: 1,
    dueThisWeek: 0,
    compliant: 14,
    source: "demo",
    identifiers: ["GSTIN 27AAAFG1234L1ZF", "LLPIN AAE-1234"],
  },
] as const;

export const workItems: readonly WorkItem[] = [
  { id: "w1", title: "Verify IGST rate changes for pharma intermediates", clientId: "sharma", client: "Sharma Pharma", authority: "CBIC", due: "Immediate", urgency: "high", state: "needs-review" },
  { id: "w2", title: "Review overdue FSSAI transition confirmation", clientId: "royal", client: "Royal Spice", authority: "FSSAI", due: "Overdue", urgency: "high", state: "needs-review" },
  { id: "w3", title: "Prepare TDS return 26Q working papers", clientId: "sharma", client: "Sharma Pharma", authority: "CBDT", due: "15 May", urgency: "medium", state: "draft-ready" },
  { id: "w4", title: "Review Karnataka overtime policy amendment", clientId: "nexgen", client: "NexGen IT", authority: "Karnataka Labour", due: "1 Jul", urgency: "medium", state: "upcoming" },
] as const;

export const regulations: readonly Regulation[] = [
  {
    id: "r1",
    title: "IGST rate schedule revised for pharma intermediates",
    authority: "CBIC",
    published: "28 Apr 2026",
    effective: "1 May 2026",
    impact: "3 demo clients",
    verification: "unverified",
    evidence: {
      state: "unverified",
      source: null,
      applicability: "Illustrative mapping to three demo client profiles.",
      reviewState: "not-reviewed",
      reviewedBy: null,
      caveat: "The prototype did not include an official circular or notification. Verify on CBIC before use.",
    },
  },
  {
    id: "r2",
    title: "Director KYC moves to a three-year cycle",
    authority: "MCA",
    published: "24 Apr 2026",
    effective: "Immediate",
    impact: "5 demo clients",
    verification: "unverified",
    evidence: {
      state: "unverified",
      source: null,
      applicability: "Illustrative mapping to five demo company profiles.",
      reviewState: "not-reviewed",
      reviewedBy: null,
      caveat: "No MCA notification or rule text is attached. Confirm the requirement and effective date before advising a client.",
    },
  },
  {
    id: "r3",
    title: "FSSAI licensing amendment introduces perpetual validity",
    authority: "FSSAI",
    published: "10 Mar 2026",
    effective: "10 Mar 2026",
    impact: "1 demo client",
    verification: "unverified",
    evidence: {
      state: "unverified",
      source: null,
      applicability: "Illustrative mapping to Royal Spice Kitchen.",
      reviewState: "not-reviewed",
      reviewedBy: null,
      caveat: "No FSSAI order or advisory is attached. Confirm licence category, jurisdiction, and transition rules.",
    },
  },
] as const;

export function getClient(id: string): Client | undefined {
  return clients.find((client) => client.id === id);
}
